export const vDOMType = {
    EXTERNAL_SOURCE: "EXTERNAL_SOURCE",
    INTERNAL_SOURCE: "INTERNAL_SOURCE",
    ATOM: "ATOM",
    MOLECULE: "MOLECULE",
    ORGANISM: "ORGANISM",
    TEMPLATE: "TEMPLATE",
    PAGE: "PAGE"
};