export const vDOMType = {
    ATOM_ELEMENT: "ATOM",
    MOLECULE_ELEMENT: "MOLECULE",
    ORGANISM_ELEMENT: "ORGANISM",
    TEMPLATE_ELEMENT: "TEMPLATE",
    MICROFRONT_WRAPPER_ELEMENT: "MICROFRONT_WRAPPER_ELEMENT",
    ELEMENT: "ELEMENT",
    PAGE: "PAGE"
};